name: 'Continuous Benchmark'
author: 'rhysd <https://rhysd.github.io>'
description: 'Continuous Benchmark using GitHub pages as dash board for keeping performance'
branding:
  icon: 'fast-forward'
  color: 'blue'

inputs:
  name:
    description: 'Name of the benchmark. This value must be identical among all benchmarks'
    required: true
    default: 'Benchmark'
  tool:
    description: 'Tool to use get benchmark output. One of "cargo", "go", "benchmarkjs", "pytest"'
    required: true
  output-file-path:
    description: 'A path to file which contains the benchmark output'
    required: true
  gh-pages-branch:
    description: 'Branch for gh-pages'
    required: true
    default: 'gh-pages'
  benchmark-data-dir-path:
    description: 'Path to directory which contains benchmark files on GitHub pages branch'
    required: true
    default: 'dev/bench'
  github-token:
    description: 'GitHub API token to pull/push GitHub pages branch and deploy GitHub pages. For public repository, this must be personal access token for now. Please read README.md for more details'
    required: false
  auto-push:
    description: 'Push GitHub Pages branch to remote automatically. This option requires github-token input'
    required: false
    default: false
  skip-fetch-gh-pages:
    description: 'Skip pulling GitHub Pages branch before generating an auto commit'
    required: false
    default: false
  alert-comment:
    description: 'Leave an alert comment when current benchmark result is worse than previous. Threshold is specified with alert-comment-threshold input. To enable this feature, github-token input must be given as well'
    required: false
    default: true
  alert-comment-threshold:
    description: 'Threshold which determines if an alert comment should be left or not. Percentage value such as "150%". For example, 150% means that an alert comment happens when current benchmark result is 1.5x worse than previous'
    required: false
    default: '200%'

runs:
  using: 'node12'
  main: 'index.js'
