name: 'Continuous Benchmark'

description: 'Continuous Benchmark using GitHub pages as dash board'

inputs:
  name:
    description: 'Name of the benchmark. This value must be identical among all benchmarks'
    required: true
    default: 'Benchmark'
  tool:
    description: 'Tool to use get benchmark output. One of "cargo", "go", "benchmarkjs"'
    required: true
  output-file-path:
    description: 'A path to file which contains the benchmark output'
    required: true
  gh-pages-branch:
    description: 'Branch for gh-pages'
    required: true
    default: 'gh-pages'
  benchmark-data-dir-path:
    description: 'Path to directory which contains benchmark files on GitHub pages branch'
    required: true
    default: 'dev/bench'
  github-token:
    description: 'GitHub API token to pull/push GitHub pages branch and deploy GitHub pages. For public repository, this must be personal access token. Please read README.md for more details'
    required: false
  auto-push:
    description: 'Push GitHub Pages branch to remote automatically. This option requires github-token input'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'index.js'
