name: Go Example
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Run Go benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
      - name: Run benchmark
        run: cd examples/go && go test -bench 'BenchmarkFib' | tee output.txt
      - name: Fetch gh-pages for avoiding conflict
        run: git fetch 'https://rhysd:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/rhysd/github-action-benchmark.git' gh-pages:gh-pages
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: examples/go/output.txt
      - name: Push benchmark result
        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
        run: git push 'https://rhysd:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/rhysd/github-action-benchmark.git' gh-pages:gh-pages
